' Gambas module file

PRIVATE EXTERN XOpenDisplay(display_name AS String) AS Pointer IN "libX11"
PRIVATE EXTERN XCloseDisplay(display AS Pointer) AS Integer IN "libX11"
PRIVATE EXTERN XkbGetIndicatorState(display AS Pointer, keycode AS Integer, return_value AS Pointer) AS Integer IN "libX11"

PUBLIC FUNCTION CapsLockIsOn() AS Boolean
  
  DIM display AS Pointer
  DIM tmp AS Integer
  DIM ptr AS Pointer
  DIM result AS Boolean
  
  ptr = Alloc(4) 'Alloc(8) in 64bit
  display = XOpenDisplay(NULL)
  XkbGetIndicatorState(display, 256, ptr)
  READ #ptr, tmp
  result = (tmp AND &h1) = 1
  XCloseDisplay(display)
  Free(ptr)
  
  RETURN result
END
